# Pre-commit configuration for La Factoria - Minimal & Functional
# Optimized for AI-assisted development workflows with performance enhancements

repos:
  # Critical file checks only - optimized with type detection
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        types: [json]  # Performance: Use type detection instead of regex
      - id: check-yaml
        types: [yaml]  # Performance: Use type detection instead of regex
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude_types: [markdown]  # More precise than regex exclusion
      - id: end-of-file-fixer
        exclude_types: [markdown]  # More precise than regex exclusion

  # Claude Code functionality checks - optimized
  - repo: local
    hooks:
      - id: claude-settings-validation
        name: Ensure Claude Code can function
        entry: python3
        args: ['-m', 'json.tool', '.claude/settings.json']
        language: system
        types: [json]
        files: ^\.claude/settings\.json$
        pass_filenames: false

      # Medium-tier validation on push only (not every commit)
      - id: context-validation-on-push
        name: Validate context changes on push
        entry: python3
        args: ['.claude/validation/scripts/validate_context.py']
        language: system
        types: [markdown]
        files: ^\.claude/context/.*\.md$
        stages: [pre-push]
        pass_filenames: false

# Performance-optimized configuration
ci:
  skip: [context-validation-on-push]  # Skip heavy validation in CI
