services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # This now refers to the multi-stage root Dockerfile
    ports:
      - "8000:8000" # Backend exposed on 8000
      - "80:80"       # Frontend (via Nginx) will be on 80
    env_file:
      - .env # Load environment variables from root .env file
    volumes:
      - ./app:/opt/app_code/app # Mount the new app code for development
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx config if you create one
    # command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload & nginx -g 'daemon off;'" # Example for running both
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # frontend: # No longer needed if served by Nginx in the same container
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    # ports:
    #   - "5173:5173"
    # volumes:
    #   - ./frontend/src:/app/src
    # command: npm run dev

volumes:
  postgres_data: # Example if you add a database service 