# Enhanced Alertmanager Configuration
# This configuration includes real integrations for Slack, PagerDuty, and Email

global:
  resolve_timeout: 5m

  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'

  # SMTP configuration for email
  smtp_from: '${ALERT_EMAIL_FROM:-alerts@lafactoria.ai}'
  smtp_smarthost: '${SMTP_HOST:-smtp.gmail.com}:${SMTP_PORT:-587}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Templates for consistent formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service', 'severity']

  # How long to wait before sending initial notification
  group_wait: 10s

  # How long to wait before sending updated notification
  group_interval: 10s

  # How long to wait before resending notification
  repeat_interval: 12h

  # Default receiver
  receiver: 'default-receiver'

  # Routing tree
  routes:
    # Critical alerts - immediate PagerDuty + Slack
    - match:
        severity: critical
      receiver: critical-alerts
      group_wait: 0s
      repeat_interval: 2h
      continue: true

    # Security incidents - special handling
    - match_re:
        alertname: '^Security.*'
      receiver: security-alerts
      group_wait: 0s
      repeat_interval: 30m

    # Database alerts - to database team
    - match:
        service: database
      receiver: database-team
      group_wait: 30s
      repeat_interval: 4h

    # External API issues - less urgent
    - match:
        service: external-api
      receiver: external-api-alerts
      group_wait: 5m
      repeat_interval: 24h

    # High priority alerts
    - match:
        severity: high
      receiver: high-priority
      group_wait: 1m
      repeat_interval: 4h

    # Development environment
    - match:
        environment: development
      receiver: dev-alerts
      group_wait: 5m
      repeat_interval: 24h

    # SLA violations
    - match:
        alertname: SLAViolation
      receiver: sla-alerts
      group_wait: 0s
      repeat_interval: 1h

# Notification receivers
receivers:
  - name: 'default-receiver'
    slack_configs:
      - channel: '${SLACK_CHANNEL_WARNINGS:-#alerts}'
        title: 'La Factoria Alert'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

  - name: 'critical-alerts'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_INTEGRATION_KEY}'
        description: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        client: 'La Factoria Alertmanager'
        client_url: '{{ template "pagerduty.default.clientURL" . }}'
        details:
          severity: '{{ .CommonLabels.severity }}'
          service: '{{ .CommonLabels.service }}'
          environment: '{{ .CommonLabels.environment }}'
    slack_configs:
      - channel: '${SLACK_CHANNEL_CRITICAL:-#alerts-critical}'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
        actions:
          - type: button
            text: 'View Runbook'
            url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
          - type: button
            text: 'View Dashboard'
            url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL:-oncall@lafactoria.ai}'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        html: |
          <h2>🚨 Critical Alert</h2>
          <p><strong>{{ .GroupLabels.alertname }}</strong></p>
          {{ range .Alerts }}
          <hr>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Service:</strong> {{ .Labels.service }}</p>
          <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          <p>
            <a href="{{ .Annotations.runbook_url }}">View Runbook</a> |
            <a href="{{ .Annotations.dashboard_url }}">View Dashboard</a>
          </p>
          {{ end }}

  - name: 'security-alerts'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SECURITY_KEY:-${PAGERDUTY_INTEGRATION_KEY}}'
        description: 'SECURITY: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        severity: critical
    slack_configs:
      - channel: '${SLACK_CHANNEL_SECURITY:-#security-alerts}'
        title: '🔴 SECURITY INCIDENT'
        text: |
          {{ range .Alerts }}
          *Type:* {{ .Labels.incident_type }}
          *Summary:* {{ .Annotations.summary }}
          *Source:* {{ .Labels.source_ip }}

          ⚠️ DO NOT ACKNOWLEDGE - Follow security protocol
          {{ end }}
    email_configs:
      - to: '${ALERT_EMAIL_SECURITY:-security@lafactoria.ai}'
        headers:
          Subject: '[SECURITY] Incident Detected'
          Priority: urgent

  - name: 'database-team'
    slack_configs:
      - channel: '${SLACK_CHANNEL_DATABASE:-#database-alerts}'
        title: 'Database Alert: {{ .GroupLabels.alertname }}'
        send_resolved: true
    email_configs:
      - to: '${ALERT_EMAIL_DATABASE:-database@lafactoria.ai}'
        headers:
          Subject: '[Database] {{ .GroupLabels.alertname }}'

  - name: 'high-priority'
    slack_configs:
      - channel: '${SLACK_CHANNEL_WARNINGS:-#alerts}'
        title: '⚠️ {{ .GroupLabels.alertname }}'
        send_resolved: true
    webhook_configs:
      - url: 'http://la-factoria-api:8000/alerts/webhook'
        send_resolved: true

  - name: 'external-api-alerts'
    slack_configs:
      - channel: '${SLACK_CHANNEL_WARNINGS:-#alerts}'
        title: 'External API Issue: {{ .CommonLabels.service }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'dev-alerts'
    slack_configs:
      - channel: '${SLACK_CHANNEL_DEV:-#dev-alerts}'
        title: '[DEV] {{ .GroupLabels.alertname }}'
        send_resolved: false

  - name: 'sla-alerts'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_INTEGRATION_KEY}'
        description: 'SLA VIOLATION: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        severity: error
    slack_configs:
      - channel: '${SLACK_CHANNEL_CRITICAL:-#alerts-critical}'
        title: '📊 SLA Violation'
    email_configs:
      - to: '${ALERT_EMAIL_MANAGER:-manager@lafactoria.ai}'
        headers:
          Subject: '[SLA] Violation Detected'

# Inhibition rules to prevent alert storms
inhibit_rules:
  # Critical alerts suppress warnings for same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

  # If entire service is down, suppress individual endpoint alerts
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '^Endpoint.*'
    equal: ['service']

  # During deployment, suppress certain alerts
  - source_match:
      alertname: 'DeploymentInProgress'
    target_match_re:
      alertname: '^(HighErrorRate|SlowResponse)$'
    equal: ['service']

# Mute time periods (e.g., maintenance windows)
mute_time_intervals:
  - name: weekly-maintenance
    time_intervals:
      - weekdays: ['sunday']
        hours:
          start_time: '02:00'
          end_time: '04:00'
        location: 'UTC'

  - name: business-hours-only
    time_intervals:
      - weekdays: ['monday:friday']
        hours:
          start_time: '09:00'
          end_time: '17:00'
        location: 'America/New_York'
