global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: pagerduty
      continue: true
    - match:
        severity: warning
      receiver: slack-warnings
    - match:
        service: database
      receiver: database-team

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'pagerduty'
    pagerduty_configs:
      - service_key: '<YOUR_PAGERDUTY_SERVICE_KEY>'
        description: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        client: 'La Factoria Prometheus'
        client_url: 'http://localhost:9090'

  - name: 'slack-warnings'
    slack_configs:
      - api_url: '<YOUR_SLACK_WEBHOOK_URL>'
        channel: '#alerts'
        title: 'La Factoria Alert'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

  - name: 'database-team'
    email_configs:
      - to: 'database-team@lafactoria.ai'
        from: 'alerts@lafactoria.ai'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alerts@lafactoria.ai'
        auth_password: '<YOUR_EMAIL_PASSWORD>'
        headers:
          Subject: 'Database Alert: {{ .GroupLabels.alertname }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
