name: AI Context Dump & Summary

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate AI context dump and summary
        run: |
          python scripts/generate_ai_context.py

      - name: Upload context dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-context-dump
          path: ai_context/ai_context_dump.md

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-context-summary
          path: ai_context/ai_context_summary.md
