name: Frontend CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build_and_test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    permissions: read-all

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x] # Using LTS version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test -- --run # Explicitly run tests once

      - name: Build project
        run: npm run build
