name: Quick Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/quick-test.yml'

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run critical tests
      env:
        DATABASE_URL: sqlite:///./test.db
        ENVIRONMENT: test
      run: |
        # Run only critical test modules for quick feedback
        python -m pytest \
          tests/test_validation.py \
          tests/test_api_endpoints.py \
          tests/test_services.py \
          tests/test_database_integration.py \
          -v --tb=short \
          --maxfail=5 \
          -x
    
    - name: Quick coverage check
      run: |
        python -m pytest tests/ --cov=src --cov-report=term-missing --quiet | tail -10